image: node:18

pipelines:
  default:
    - step:
        name: Build and Deploy to S3
        caches:
          - node
        script:
          - npm install
          - npm run build
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: "dongjiaocleaning-dev"
              LOCAL_PATH: "dist"
